version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "pip"
      include: "scope"
    groups:
      pip-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /search-worker
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "Worker npm"
      include: "scope"
    groups:
      worker-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /sunset
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "Worker npm"
      include: "scope"
    groups:
      sunset-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /redirector
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "Worker npm"
      include: "scope"
    groups:
      redirector-minor-and-patch:
        update-types:
          - minor
          - patch
